on: push
name: Deploy website
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Build Project
        run: |
          npm install
          CI='' npm run build

      - name: List output files
        run: find build/ -print

      - name: Sync files
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          localPath: "./build"
          remotePath: "./"
